<?php

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\editor\EditorInterface;
use Drupal\text\Plugin\Field\FieldType\TextItemBase;

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor5_highlight_preprocess_field(array &$variables): void {
  $items = $variables['element']['#items'];
  if (!$items instanceof FieldItemListInterface) {
    return;
  }

  foreach ($items as $item) {
    if (!$item instanceof TextItemBase) {
      continue;
    }

    $editor = \Drupal::entityTypeManager()
      ->getStorage('editor')
      ->load($item->format);
    if (!$editor instanceof EditorInterface) {
      continue;
    }

    if ($editor->getEditor() !== 'ckeditor5') {
      continue;
    }

    $settings = $editor->getSettings();
    if (in_array('highlight', $settings['toolbar']['items'], TRUE)) {
      $variables['#attached']['library'][] = 'ckeditor5_highlight/theme';
    }
  }
}
