<?php

/**
 * @file
 * Contains find_replace.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

function find_replace_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the find_replace module.
    case 'help.page.find_replace':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This plugin module adds the find and replace dialog to CKEditor in Drupal 8') . '</p>';
      $output .= '<p><ul>';
      $output .= '  <li>Quickly search the text as well as replace words inside it.</li>';
      $output .= '  <li>Common options available for matching: ';
      $output .= '    <ul>';
      $output .= '      <li>case</li>';
      $output .= '      <li>whole word</li>';
      $output .= '      <li>cyclic</li>';
      $output .= '    </ul>';
      $output .= '  </li>';
      $output .= '</ul></p>';
      $output .= '<p><a href="http://ckeditor.com/addon/find">http://ckeditor.com/addon/find</a></p>';
      return $output;

    default:
  }
}
