ckeditor5.plugin.ckeditor5_plugin_pack_font__font_size:
  type: mapping
  label: 'Font Size'
  mapping:
    options:
      type: string

ckeditor5.plugin.ckeditor5_plugin_pack_font__font_family:
  type: mapping
  label: 'Font Family'
  mapping:
    options:
      type: string
    support_all_values:
      type: boolean
