<?php

/*
 * Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

use Drupal\ckeditor5_plugin_pack_word_count\Element\TextFormat;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_word_count_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['word-count']);
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_plugin_pack_word_count_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
  }
}
